included: # paths to include during linting. `--path` is ignored if present.
  - weather
excluded: # paths to ignore during linting. overridden by `included`.
  - Pods
line_length:
  - 200
reporter: "xcode"
